name: MyFinance CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-backend:
    name: Backend test (.NET)
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: .NET install
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: backend test run
        run: |
          dotnet restore ./myfinance-project.sln
          dotnet build ./myfinance-project.sln
          dotnet test ./backend.Tests/backend.Tests.csproj

  build-frontend:
    name: Frontend Build (React)
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Node.js install
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: dependency install
        working-directory: ./frontend
        run: |
          npm install
          npm run build
